const loginPage = require("../pageobjects/login.page.js")
const catalogPage = require("../pageobjects/catalog.page.js")
//Log In
    beforeAll(() =>{  
        loginPage.open()
        loginPage.username.setValue("standard_user")
        loginPage.password.setValue("secret_sauce")
        loginPage.submit()
    })
describe("Test for catalog",() =>{  
    describe("Validation of items and his elements", () =>{
        it("Sauce Labs Backpack", () =>{
            catalogPage.item4.isExisting()
            catalogPage.btnItem4.isExisting()
            catalogPage.img1.getAttribute("alt")
            expect(catalogPage.img4.getAttribute("alt")).toMatch("Sauce Labs Backpack")
            catalogPage.description[0].isExisting()
            catalogPage.price[0].isExisting()
        })
        it("Sauce Labs Bike Light", () =>{
            catalogPage.item0.isExisting()
            catalogPage.btnItem0.isExisting()
            expect(catalogPage.img0.getAttribute("alt")).toMatch("Sauce Labs Bike Light")
            catalogPage.description[1].isExisting()
            catalogPage.price[1].isExisting()
        })
        it("Sauce Labs Bolt T-Shirt", () =>{
            catalogPage.item1.isExisting()
            catalogPage.btnItem1.isExisting()
            expect(catalogPage.img1.getAttribute("alt")).toMatch("Sauce Labs Bolt T-Shirt")
            catalogPage.description[2].isExisting()
            catalogPage.price[2].isExisting()
        })
        it("Sauce Labs Fleece Jacket", () =>{
            catalogPage.item5.isExisting()
            catalogPage.btnItem5.isExisting()
            expect(catalogPage.img5.getAttribute("alt")).toMatch("Sauce Labs Fleece Jacket")
            catalogPage.description[3].isExisting()
            catalogPage.price[3].isExisting()
        })
        it("Sauce Labs Onesie", () =>{
            catalogPage.item2.isExisting()
            catalogPage.btnItem2.isExisting()
            expect(catalogPage.img2.getAttribute("alt")).toMatch("Sauce Labs Onesie")
            catalogPage.description[4].isExisting()
            catalogPage.price[4].isExisting()
        }) 
        it("Test.allTheThings() T-Shirt (Red)", () =>{
            catalogPage.item3.isExisting()
            catalogPage.btnItem3.isExisting()
            expect(catalogPage.img3.getAttribute("alt")).toContain("Test.allTheThings")
            catalogPage.description[5].isExisting()
            catalogPage.price[5].isExisting()
        })
    })
    describe("Add to cart the diferrents items and remove them", () =>{
        it("Sauce Labs Bike Light", () =>{
            catalogPage.btnItem0.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem0.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
        })
        it("Sauce Labs Bolt T-Shirt", () =>{
            catalogPage.btnItem1.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem1.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
        })
        it("Sauce Labs Fleece Jacket", () =>{
            catalogPage.btnItem2.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem2.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)  
        })
        it("Sauce Labs Onesie", () =>{
            catalogPage.btnItem3.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem3.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined) 
        }) 
        it("Sauce Labs Backpack", () =>{
            catalogPage.btnItem4.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem4.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
        })
        it("Test.allTheThings() T-Shirt (Red)", () =>{
            catalogPage.btnItem5.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem5.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)  
        })
        it("Add multiple items and remove them", () =>{
            catalogPage.btnItem0.click()
            catalogPage.btnItem1.click()
            catalogPage.btnItem2.click()
            catalogPage.btnItem3.click()
            catalogPage.btnItem4.click()
            catalogPage.btnItem5.click()
            expect(catalogPage.spanCart).toHaveText("6")
            catalogPage.removeItem5.click()
            expect(catalogPage.spanCart).toHaveText("5")
            catalogPage.removeItem4.click()
            expect(catalogPage.spanCart).toHaveText("4")
            catalogPage.removeItem3.click()
            expect(catalogPage.spanCart).toHaveText("3")
            catalogPage.removeItem2.click()
            expect(catalogPage.spanCart).toHaveText("2")
            catalogPage.removeItem1.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem0.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)  
        })
    })
    describe("Burger Menu", () => {
        it("Button to open Burger menu and close it", () =>{
            catalogPage.btnBurger.isExisting()
            catalogPage.btnBurger.click()
            catalogPage.btnBurgerClose.isExisting()
            expect(catalogPage.btnBurgerClose.getAttribute("tabindex")).toEqual("0")
            catalogPage.btnBurgerClose.click()
            expect(catalogPage.btnBurgerClose.getAttribute("tabindex")).toEqual("-1")
        })
        describe("Burger Menu items tests", () =>{
            beforeAll(() =>
                catalogPage.btnBurger.click()
            )
            it("All items button", () =>{
                catalogPage.linkAllItems.isExisting()
                expect(catalogPage.linkAllItems.getAttribute("href")).toEqual("https://www.saucedemo.com/inventory.html#")
            })
            it("About button", () =>{
                catalogPage.linkAbout.isExisting()
                expect(catalogPage.linkAbout.getAttribute("href")).toEqual("https://saucelabs.com/")
            })  
            it("Reset App State button", () =>{
                catalogPage.linkReset.isExisting()
                catalogPage.btnItem1.click()
                expect(catalogPage.linkReset.getAttribute("href")).toEqual("https://www.saucedemo.com/inventory.html#")
                catalogPage.linkReset.click()
                expect(catalogPage.spanCart[0]).toEqual(undefined)
            })
            it("Logout button", () =>{
                catalogPage.linkLogout.isExisting()
                catalogPage.linkLogout.click()
                expect(browser).toHaveUrl("https://www.saucedemo.com/")
                loginPage.username.setValue("standard_user")
                loginPage.password.setValue("secret_sauce")
                loginPage.submit()
            })

        })
    })
    describe("Selector for sort items", () => {
        it("Selector existing",() =>{
        catalogPage.selector.isExisting()
        catalogPage.selector.selectByAttribute("value","az")
        expect(catalogPage.selector.getText()).toContain("Name (A to Z)")
        expect(catalogPage.selector.getText()).toContain("Name (Z to A)")
        expect(catalogPage.selector.getText()).toContain("Price (low to high)")
        expect(catalogPage.selector.getText()).toContain("Price (high to low)")
        }) 
    })
    describe("Social media", () => {

        it("Twiter test", () => {
            catalogPage.twitter.getAttribute("href")
            expect(catalogPage.twitter.getAttribute("href")).toMatch("https://twitter.com/saucelabs")
        })
        it("Facebook test", () => {
            catalogPage.facebook.getAttribute("href")
            expect(catalogPage.facebook.getAttribute("href")).toMatch("https://www.facebook.com/saucelabs")
        })
        it("Linkedin test", () => {
            catalogPage.linkedin.getAttribute("href")
            expect(catalogPage.linkedin.getAttribute("href")).toMatch("https://www.linkedin.com/company/sauce-labs/")
        })
    })
    describe("Items of the inventory", () => {
        it("Sauce Labs Backpack", () =>{
            catalogPage.item4.click()
            catalogPage.imgItemDetail.isExisting()
            expect(catalogPage.imgItemDetail.getAttribute("alt")).toMatch("Sauce Labs Backpack")
            catalogPage.itemDescription.isExisting()
            catalogPage.itemPrice.isExisting()
            catalogPage.btnItem4.isExisting()
            catalogPage.btnItem4.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem4.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
            catalogPage.btnBack.isExisting()
            catalogPage.btnBack.click()
        })
        it("Sauce Labs Bike Light", () =>{
            catalogPage.item0.click()
            catalogPage.imgItemDetail.isExisting()
            expect(catalogPage.imgItemDetail.getAttribute("alt")).toMatch("Sauce Labs Bike Light")
            catalogPage.itemDescription.isExisting()
            catalogPage.itemPrice.isExisting()
            catalogPage.btnItem0.isExisting()
            catalogPage.btnItem0.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem0.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
            catalogPage.btnBack.isExisting()
            catalogPage.btnBack.click()
        })
        it("Sauce Labs Bolt T-Shirt", () =>{
            catalogPage.item1.click()
            catalogPage.imgItemDetail.isExisting()
            expect(catalogPage.imgItemDetail.getAttribute("alt")).toMatch("Sauce Labs Bolt T-Shirt")
            catalogPage.itemDescription.isExisting()
            catalogPage.itemPrice.isExisting()
            catalogPage.btnItem1.isExisting()
            catalogPage.btnItem1.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem1.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
            catalogPage.btnBack.isExisting()
            catalogPage.btnBack.click()
        })
        it("Sauce Labs Fleece Jacket", () =>{
            catalogPage.item5.click()
            catalogPage.imgItemDetail.isExisting()
            expect(catalogPage.imgItemDetail.getAttribute("alt")).toMatch("Sauce Labs Fleece Jacket")
            catalogPage.itemDescription.isExisting()
            catalogPage.itemPrice.isExisting()
            catalogPage.btnItem5.isExisting()
            catalogPage.btnItem5.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem5.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)
            catalogPage.btnBack.isExisting()  
            catalogPage.btnBack.click()
        })
        it("Sauce Labs Onesie", () =>{
            catalogPage.item2.click()
            catalogPage.imgItemDetail.isExisting()
            expect(catalogPage.imgItemDetail.getAttribute("alt")).toMatch("Sauce Labs Onesie")
            catalogPage.itemDescription.isExisting()
            catalogPage.itemPrice.isExisting()
            catalogPage.btnItem2.isExisting()
            catalogPage.btnItem2.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem2.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined)  
            catalogPage.btnBack.isExisting()
            catalogPage.btnBack.click()
        }) 
        it("Test.allTheThings() T-Shirt (Red)", () =>{
            catalogPage.item3.click()
            catalogPage.imgItemDetail.isExisting()
            expect(catalogPage.imgItemDetail.getAttribute("alt")).toMatch("Test.allTheThings")
            catalogPage.itemDescription.isExisting()
            catalogPage.itemPrice.isExisting()
            catalogPage.btnItem3.isExisting()
            catalogPage.btnItem3.click()
            expect(catalogPage.spanCart).toHaveText("1")
            catalogPage.removeItem3.click()
            expect(catalogPage.spanCart[0]).toEqual(undefined) 
            catalogPage.btnBack.isExisting()
            catalogPage.btnBack.click()
        })
    })
})